
// function calcularMediaAritmetica(Num1, Num2, Num3, Num4) {
//     // let sumaLista = 0;
//     // for (let i = 0; i < lista.length; i++) {
//     // sumaLista = sumaLista + lista[i];
//     // }
//     // // const sumaLista = lista.reduce(
//     // //     // EL .reduce() PERMITE (SUMAR, RESTAR, ETC) LOS ELEMENTOS DE UNA LISTA.
//     // //     function (valorAcumulado = 0, nuevoElemento) {
//     // //         return valorAcumulado + nuevoElemento;
//     // //     }
//     // // );
//     // const promedioLista = sumaLista / lista.length;
//     // return promedioLista;
//     const sumaLista = Num1 + Num2 + Num3 + Num4;
//     const divLista = sumaLista / 4;
//     return divLista;
// }

function onClickCalcAverage() {
    
}
